
services:
  vue-app:
    image: ghcr.io/luaysd/vue-app:latest
    ports:
      - "8090:80"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable --cleanup
