server {
    listen 80;
    server_name http://91.99.4.166;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Optional: Allow CORS if needed
    add_header Access-Control-Allow-Origin *;
}
